name: Aparaire
version: 2.0
main: siwa.valorium.Aparaire
api-version: 1.19
author: Siwa
description: Système de spectateur restreint pour visiteurs

commands:
  aparairereload:
    description: Recharge la whitelist et la configuration
    usage: /<command>
    permission: aparaire.reload
    permission-message: Tu n'as pas la permission.

permissions:
  aparaire.reload:
    description: Permet de recharger le plugin
    default: op
